namespace GdscriptTranscompiler.Tokenizing
{
    public enum TokenType
    {
        If,
        Is,
        Pi,
        Tau,
        Inf,
        Nan,
        For,
        Var,
        Pass,
        Else,
        Self,
        Elif,
        Func,
        Break,
        While,
        Yield,
        Const,
        Indent,
        Return,
        Export,
        Signal,
        OnReady,
        Extends,
        Preload,
        Continue,
        Identifier
    }
}
